### ISSUE TITLE
Unpack Next.js cache dir or provide an option to choose the dir

### ISSUE THREAD

**Issue by kirill-konshin** [kirill-konshin/next-electron-rsc#3]
A follow up for https://github.com/kirill-konshin/next-electron-rsc/issues/2#issuecomment-2458552348

There seems to be a bug in asarUnpack: https://github.com/electron-userland/electron-builder/issues/7264

The following does not work in `demo`:

```yml
asarUnpack:
  - '.next/standalone/demo/.next/cache/**/*'
```

```
  ⨯ /x/lib/.tscache/cache must be under /x/demo/  failedTask=build stackTrace=Error: /x/lib/.tscache/cache must be under /x/demo/
    at getRelativePath (/x/demo/node_modules/app-builder-lib/src/util/filter.ts:32:13)
    at AsarPackager.unpackPattern (/x/demo/node_modules/app-builder-lib/src/util/filter.ts:57:22)
    at AsarPackager.createPackageFromFiles (/x/demo/node_modules/app-builder-lib/src/asar/asarUtil.ts:129:82)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at AsarPackager.pack (/x/demo/node_modules/app-builder-lib/src/asar/asarUtil.ts:49:41)
    at /x/demo/node_modules/app-builder-lib/src/platformPackager.ts:439:11
    at async Promise.all (index 0)
    at AsyncTaskManager.awaitTasks (/x/demo/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at MacPackager.doPack (/x/demo/node_modules/app-builder-lib/src/platformPackager.ts:293:5)
    at MacPackager.pack (/x/demo/node_modules/app-builder-lib/src/macPackager.ts:215:9)
    at Packager.doBuild (/x/demo/node_modules/app-builder-lib/src/packager.ts:459:9)
    at executeFinally (/x/demo/node_modules/builder-util/src/promise.ts:12:14)
    at Packager.build (/x/demo/node_modules/app-builder-lib/src/packager.ts:393:31)
    at executeFinally (/x/demo/node_modules/builder-util/src/promise.ts:12:14)
```

**Comment by kirill-konshin** [comment]
@jamcalli for now I conclude that best option is to disable ASAR until either Next.js or Electron Builder fixes the issue...

**Comment by jamcalli** [comment]
@kirill-konshin thanks for looking into this. 

It honestly isn't a big deal, and its probably totally ok to just opt out of image optimization caching, at least for my use case. 

I appreciate your suggestions, and documenting the nuances will be beneficial for anyone encountering similar situation.

**Comment by jamcalli** [comment]
> @jamcalli for now I conclude that best option is to disable ASAR until either Next.js or Electron Builder fixes the issue...
> 
> ~Alternatively you can try to opt out of ASAR just the cache dir:~
> 
> ```yaml
> asarUnpack:
>   - '.next/standalone/demo/.next/cache/**/*'
> ```
> 
> ~It fails in demo due to monorepo, but in your case it might work, just copy there something before the packaging, so the dir will be created.~
> 
> Made it work for monorepo, does not fix the problem... Electron still tries to write in ASAR instead of the unpacked dir.

A true solution would be for next to allows specifying the cache dir. There are some tickets open regarding this, but obviously the use case is so niche that I cant see them working on it anytime soon.

**Comment by kirill-konshin** [comment]
Btw, you can safely disable ASAR: it provides minimal security, primarily through obscurity. While it does package files into a single archive, the contents can be easily extracted, meaning it doesn’t actually encrypt or truly protect the files. This “security” mainly prevents casual users from easily browsing or modifying the app’s code but does little to deter a determined attacker.

```yml
asar: false
```

No issues with cache ;)

**Comment by jamcalli** [comment]
This is true.

asar just reduces the bundle size considerably (in my case almost 50% smaller), so it is ideal to use it.
